name: Makefile CI

on:
  push:
   branches: [ "master" ]
  pull_request:
   branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Autotools
      run: autoreconf -vif

    - name: Configure
      run: ./configure

    - name: Generate exec
      run: make

    - name: Run check
      run: make check
